package com.authorss81.noteflow.plugins.runtime

/**
 * AUTO-GENERATED by `:app:generateMlKitPluginSeed` — DO NOT EDIT BY HAND.
 *
 * The application-compiled pin of the ONE real, CI-signed ML Kit plugin release
 * (com.authorss81.noteflow.plugins.mlkit, R2-KS-21). `:app:generateMlKitPluginSeed`
 * (app/build.gradle.kts) rewrites this file from the metadata of the SIGNED
 * `:plugins:mlkit` artifact — a flow that requires the real plugin-signing
 * keystore env vars (`PLUGIN_SIGNING_KEYSTORE_B64` + `PLUGIN_SIGNING_STORE_PASS`,
 * from the secret store) because it depends on `:plugins:mlkit:pluginMetadata`,
 * which fails loudly without them. So the pin can only ever match the real CI
 * signing identity, never a build-bred keystore. `CompileTimePluginPins.RELEASES`
 * folds this release into the app-compiled pin table, so the plugin-update chain
 * only ever accepts an artifact signed by that exact key.
 *
 * `null` (this committed initial state) = no ML Kit plugin release has been pinned
 * yet → the update chain refuses every offer, fail-closed (B1-NET-03). Publishing
 * a genuine release = run the seed task with the signing env set and commit the
 * resulting diff + an app bump.
 */
internal val mlKitPluginSeedRelease: PinnedPluginRelease? = null